import { siteConfig } from "@/lib/config";

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-16 prose prose-sm dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: {new Date().toISOString().split("T")[0]}</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing and using {siteConfig.name} (&quot;Service&quot;), you accept and agree to be
        bound by the terms and provisions of this agreement.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        {siteConfig.name} provides AI-powered online tools. The Service is provided
        &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        You may need to create an account to use certain features. You are responsible
        for maintaining the confidentiality of your account credentials and for all
        activities under your account.
      </p>

      <h2>4. Payment and Credits</h2>
      <p>
        Some features require credits, which can be purchased through our payment
        provider. All purchases are final. Credits do not expire but are non-transferable
        and non-refundable.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any illegal purpose</li>
        <li>Attempt to reverse engineer or copy the Service</li>
        <li>Abuse, harass, or harm other users</li>
        <li>Use automated scripts to access the Service without permission</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        Content generated by the Service using your input belongs to you. The Service
        itself, including its design, code, and branding, remains our property.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, we shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages resulting
        from your use of the Service.
      </p>

      <h2>8. Changes to Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Continued use of
        the Service after changes constitutes acceptance of the new terms.
      </p>

      <h2>9. Contact</h2>
      <p>
        For questions about these Terms, contact us at{" "}
        <a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a>.
      </p>
    </div>
  );
}
